version: "3"
services:
  latex:
    image: mirisbowring/texlive_ctan_full:2019
    container_name: texlive_full__report
    volumes:
      - ./../:/home/user/content/
    command: ["make", "-C", "/home/user/content/report"]
