build:
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PZ.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA3.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA2.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA1.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA0.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA3_portrait.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA2_portrait.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA1_portrait.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilA0_portrait.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilB.tex
	latexmk -pdf -output-directory=_build 1_coursework_PO-4_Galanin_PrilV.tex
	latexmk -pdf -output-directory=_build subject_PO-4_Galanin_lab1.tex

clean:
	rm -rfv ./*/*.aux
	rm -rfv ./*/*.fdb_latexmk
	rm -rfv ./*/*.fls
	rm -rfv ./*/*.log
	rm -rfv ./*/*.out
	rm -rfv ./*/*.pdf
	rm -rfv ./*/*.synctex.gz
	rm -rfv ./*/*.toc
