build:
	latexmk -pdf -output-directory=_build 1_курсовая_ПО-4_Галанин_ПЗ.tex
	latexmk -pdf -output-directory=_build 1_курсовая_ПО-4_Галанин_ПрилА.tex
	latexmk -pdf -output-directory=_build 1_курсовая_ПО-4_Галанин_ПрилА3.tex
	latexmk -pdf -output-directory=_build 1_курсовая_ПО-4_Галанин_ПрилБ.tex
	latexmk -pdf -output-directory=_build ДИСЦИПЛИНА_ПО-4_Галанин_лаб1.tex

clean:
	rm -rfv ./*/*.aux
	rm -rfv ./*/*.fdb_latexmk
	rm -rfv ./*/*.fls
	rm -rfv ./*/*.log
	rm -rfv ./*/*.out
	rm -rfv ./*/*.pdf
	rm -rfv ./*/*.synctex.gz
	rm -rfv ./*/*.toc
