version: '3'
services:
    latex:
        image: mirisbowring/texlive_ctan_full:2019
        container_name: latex_for_coursework__texlive_full
        volumes:
            - ./../:/home/user/content/
        command: ['make', '-C', '/home/user/content/gpi_rep']
