build:
	latexmk -pdf -output-directory=_build gpi_Ncoursework_pz.tex
	latexmk -pdf -output-directory=_build gpi_Ncoursework_a.tex
	latexmk -pdf -output-directory=_build gpi_Ncoursework_a3.tex
	latexmk -pdf -output-directory=_build gpi_Ncoursework_b.tex
	latexmk -pdf -output-directory=_build gpi_disciplineK_rep_labN.tex

clean:
	rm -rfv ./*/*.aux
	rm -rfv ./*/*.fdb_latexmk
	rm -rfv ./*/*.fls
	rm -rfv ./*/*.log
	rm -rfv ./*/*.out
	rm -rfv ./*/*.pdf
	rm -rfv ./*/*.synctex.gz
	rm -rfv ./*/*.toc
